<?xml version="1.0" encoding="utf-8"?><Database Name="pwe0916_1028717" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=kraka.ucn.dk;Initial Catalog=pwe0916_1028717;User ID=pwe0916_1028717" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="pwe0916_1028717ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Class" Member="Classes">
    <Type Name="Class">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Class_Schedule" Member="Schedules" ThisKey="ID" OtherKey="Class" Type="Schedule" />
      <Association Name="Class_User" Member="Users" ThisKey="ID" OtherKey="Class" Type="User" />
      <Association Name="Class_Homework" Member="Homeworks" ThisKey="ID" OtherKey="Class" Type="Homework" />
    </Type>
  </Table>
  <Table Name="dbo.Schedule" Member="Schedules">
    <Type Name="Schedule">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Class" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Monday" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tuesday" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Wednesday" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Thursday" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Friday" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Class_Schedule" Member="Class1" ThisKey="Class" OtherKey="ID" Type="Class" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserData" Member="UserDatas">
    <Type Name="UserData">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Logout" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Homework" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="User_UserData" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Class" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mandatory" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Type" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="User_UserData" Member="UserDatas" ThisKey="ID" OtherKey="UserID" Type="UserData" />
      <Association Name="Class_User" Member="Class1" ThisKey="Class" OtherKey="ID" Type="Class" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Homework" Member="Homeworks">
    <Type Name="Homework">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Homework" Member="Homework1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Class" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Class_Homework" Member="Class1" ThisKey="Class" OtherKey="ID" Type="Class" IsForeignKey="true" />
    </Type>
  </Table>
</Database>